### ISSUE TITLE
network of modules

### ISSUE THREAD

**Issue by haluk** [erbon7/lemon-tree#12]
I followed the tutorial, and generated heatmap figures for each cluster.

There 15 modules found with tutorial data. If I want to build a BN for these 15 modules, nodes are modules and edges are dependency relationships between modules, which task I should use?

**Comment by erbon7** [comment]
Hi haluk, sorry for this (very) late answer. The task is "regulators" which will assigne candidate regulators for all modules. A given regulator may be assigned to multiple modules, so you really get a module network.

**Comment by tmichoel** [comment]
See issue #13 for a complete response.
